/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.concurrent.Semaphore;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;

/**
 *
 * @author m_luc
 */
public class ServerWindow extends javax.swing.JFrame {
    private static final int PORT = 12345;
    private static final int MAX_CLIENTS = 2;
    private static int clientCount = 0;
    private static final Semaphore semaphore = new Semaphore(MAX_CLIENTS);
    private static final String LOG_FILE = "server_log.txt";
    private static final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private boolean logToFile = false;
    private static ServerWindow instance;

    public ServerWindow() {
        initComponents();
        instance = this;
        startServer();
    }

    private void startServer() {
        new Thread(() -> {
            try (ServerSocket serverSocket = new ServerSocket(PORT)) {
                logMessage("Server started. Waiting for connections...");

                while (true) {
                    Socket clientSocket = serverSocket.accept();

                    try {
                        semaphore.acquire();
                        clientCount++;
                        int clientId = clientCount;
                        logMessage("Client #" + clientId + " connected. Current clients: " + clientCount);

                        new Thread(() -> handleClient(clientSocket, clientId)).start();
                    } catch (InterruptedException e) {
                        logError("Semaphore error: " + e.getMessage());
                        clientSocket.close();
                    }
                }
            } catch (IOException e) {
                logError("Server error: " + e.getMessage());
            }
        }).start();
    }

    public static void logMessage(String message) {
        String timestamp = LocalDateTime.now().format(dtf);
        String logMessage = timestamp + " - " + message;

        if (instance != null) {
            SwingUtilities.invokeLater(() -> {
                instance.jTextArea1.append(logMessage + "\n");
                instance.jTextArea1.setCaretPosition(instance.jTextArea1.getDocument().getLength());
            });
        }

        System.out.println(logMessage);

        if (instance != null && instance.logToFile) {
            try {
                Files.write(Paths.get(LOG_FILE),
                        (logMessage + "\n").getBytes(),
                        StandardOpenOption.CREATE,
                        StandardOpenOption.APPEND);
            } catch (IOException e) {
                System.err.println("Failed to write to log file: " + e.getMessage());
            }
        }
    }

    public static void logError(String error) {
        String timestamp = LocalDateTime.now().format(dtf);
        String logMessage = timestamp + " - ERROR: " + error;

        if (instance != null) {
            SwingUtilities.invokeLater(() -> {
                instance.jTextArea1.append(logMessage + "\n");
                instance.jTextArea1.setCaretPosition(instance.jTextArea1.getDocument().getLength());
            });
        }

        System.err.println(logMessage);

        if (instance != null && instance.logToFile) {
            try {
                Files.write(Paths.get(LOG_FILE),
                        (logMessage + "\n").getBytes(),
                        StandardOpenOption.CREATE,
                        StandardOpenOption.APPEND);
            } catch (IOException e) {
                System.err.println("Failed to write to log file: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Server Log"));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Server tools"));

        jRadioButton1.setText("Лог в файл");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRadioButton1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        logToFile = jRadioButton1.isSelected();
        logMessage("File logging " + (logToFile ? "enabled" : "disabled"));
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private static void handleClient(Socket clientSocket, int clientId) {
        try (BufferedReader in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
             PrintWriter out = new PrintWriter(clientSocket.getOutputStream(), true)) {

            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                try {
                    logMessage("Received from client #" + clientId + ": " + inputLine);
                    String result = calculateExpression(inputLine);
                    String response = "Result: " + result;
                    out.println(response);
                    logMessage("Sent to client #" + clientId + ": " + response);
                } catch (IllegalArgumentException e) {
                    String error = "Error: " + e.getMessage();
                    out.println(error);
                    logError("Error processing client #" + clientId + " input: " + e.getMessage());
                }
            }
        } catch (IOException e) {
            logError("Error handling client #" + clientId + ": " + e.getMessage());
        } finally {
            try {
                clientSocket.close();
                semaphore.release();
                clientCount--;
                logMessage("Client #" + clientId + " disconnected. Current clients: " + clientCount);
            } catch (IOException e) {
                logError("Error closing socket for client #" + clientId + ": " + e.getMessage());
            }
        }
    }

    private static String calculateExpression(String expression) {
        String cleaned = expression.replaceAll("\\s+", "");

        int opPos = findOperatorPosition(cleaned);
        if (opPos == -1 || opPos == 0 || opPos == cleaned.length() - 1) {
            throw new IllegalArgumentException("Invalid input format - operator not found or misplaced");
        }

        try {
            double num1 = Double.parseDouble(cleaned.substring(0, opPos));
            double num2 = Double.parseDouble(cleaned.substring(opPos + 1));
            char op = cleaned.charAt(opPos);

            double result = calculate(num1, num2, op);
            return String.valueOf(result);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Invalid numbers format");
        }
    }

    private static int findOperatorPosition(String str) {
        for (int i = 0; i < str.length(); i++) {
            char c = str.charAt(i);
            if (c == '+' || c == '-' || c == '*' || c == '/') {
                if (i == 0 && c == '-') continue;
                return i;
            }
        }
        return -1;
    }

    private static double calculate(double a, double b, char op) {
        switch (op) {
            case '+': return a + b;
            case '-': return a - b;
            case '*': return a * b;
            case '/':
                if (b == 0) throw new IllegalArgumentException("Division by zero");
                return a / b;
            default: throw new IllegalArgumentException("Invalid operator: " + op);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            ServerWindow window = new ServerWindow();
            window.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
